dependencies:
- alias: tekton
  name: tekton
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.39
- alias: prow
  name: prow
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.787
- name: jenkins-x-platform
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 2.0.634
- name: jenkins-x-platform
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 2.0.634
